<?php
declare(strict_types=1);

namespace Kalma\API\Test\Core;

require __DIR__ . '/../../vendor/autoload.php';

use PHPUnit\Framework\TestCase;
use Kalma\Api\Core\Auth;


final class AuthTest extends TestCase
{
    /**
     * Test that a JWT can be generated given a valid access level and user id
     * @return string
     */
    public function testGeneratesValidJwt() : array
    {
        $payload = array('dummy' => 42);
        $jwt = Auth::generateJWT($payload);

        self::assertNotNull($jwt);

        return [$payload, $jwt];
    }

    /**
     * Test that a valid JWT can be validated
     * @depends testGeneratesValidJwt
     * @param   array The payload and resulting JWT generated by testGeneratesValidJwt
     */
    public function testValidatesValidJwt(array $input) : void
    {
        [$payload, $jwt] = $input;
        $res = Auth::validateJWT($jwt);

        self::assertTrue($res['success']);
        self::assertEquals($payload, $res['payload']);
    }
}